name: Java CI with Maven
run-name: ${{ github.actor }} attempted to make changes on main branch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: oracle-actions/setup-java@v1
      with:
        website: oracle.com
        release: 19
    - name: Validate, build and run tests
      run: mvn --batch-mode --update-snapshots verify
